spring.application.name=api-service
server.address=127.0.0.1
server.port=8080

# Exponer unicamente el estado de salud de la aplicacion
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never