# Conexion a PostgreSQL en Azure
spring.datasource.url=${AZURE_POSTGRES_URL}
spring.datasource.username=${AZURE_POSTGRES_USERNAME}
spring.datasource.password=${AZURE_POSTGRES_PASSWORD}

# Comprobar el esquema sin modificarlo
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false